### ISSUE TITLE
error in code slide 44 ML082_bayes_202115n.pdf?

### ISSUE THREAD

**Issue by Sandy4321** [Dyakonov/MSUML#2]
error in code slide 44 ML082_bayes_202115n.pdf?
 for
https://github.com/Dyakonov/MSUML/blob/main/2022spring/ML082_bayes_202115n.pdf

by the way is BayesianRidge  to slow ?

from sklearn.linear_model import BayesianRidge 
# обучение model = BayesianRidge() 
x = np.vander(x, 4) model.fit(x,y) 
# формируем ответ 
grid = np.linspace(-3, 3, 100) 
x2 = np.vander(grid, 4) 
means, stds = model.predict(x2, return_std=True)

![image](https://user-images.githubusercontent.com/11426119/165346889-d3e34412-5dc5-4342-94f7-bc4de019af32.png)

**Comment by Dyakonov** [comment]
no error, BayesianRidge  is slower than regular Ridge regression

**Comment by Sandy4321** [comment]
but x and y used before was created ?

**Comment by Sandy4321** [comment]
by the way , can you share video for 
https://github.com/Dyakonov/MSUML/blob/main/2022spring/PZAD071_RecSys_202201a____.pdf

**Comment by Sandy4321** [comment]
Any answer pls

**Comment by Dyakonov** [comment]
> but x and y used before was created ?

x and y should not be created in this code. This is the data for a polynomial regression. x and y defined before this snippet.

**Comment by Sandy4321** [comment]
can you share full code pls
